version: 0.2

phases:
  install:
    commands:
      - echo Install step empty
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Kotlin code...
      - pwd
      - ls
      - mvn compile
      - ls target
      - ls target/*
      - ls target/classes/*
      - mvn package
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/chess_ai-0.0.1.jar