version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y build-essential
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Kotlin code...
      - mvn compile
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/chess_ai-0.0.1.jar